FROM archlinux

WORKDIR /usr/src/oxyromon
COPY . .
RUN sed 's/^SigLevel    =.*/SigLevel = Never/' -i /etc/pacman.conf && \
    pacman -Syu --noconfirm base-devel bchunk curl dolphin-emu-tool mame-tools maxcso p7zip rustup wit && \
    rustup toolchain install stable && \
    rustup target add wasm32-unknown-unknown && \
    curl -fsSL https://github.com/trunk-rs/trunk/releases/download/v0.21.14/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf- -C /usr/local/bin && \
    curl -fsSL https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -o /usr/local/bin/tailwindcss && \
    chmod +x /usr/local/bin/tailwindcss && \
    cargo install \
    --features server \
    --root /usr \
    --path . && \
    cargo clean && \
    rm -rf /root/.cargo /root/.rustup /root/.cache /usr/local/bin/trunk /usr/local/bin/tailwindcss /tmp/* && \
    pacman -Rns --noconfirm base-devel rustup && \
    pacman -Sc --noconfirm

WORKDIR /
RUN rm -rf /usr/src/oxyromon

ENV OXYROMON_DATA_DIRECTORY=/data \
    OXYROMON_ROM_DIRECTORY=/roms

VOLUME [ "/data", "/roms" ]

CMD ["oxyromon"]
