INSERT OR REPLACE INTO settings ("key", value)
VALUES('DISCARD_FLAGS', NULL);

INSERT OR REPLACE INTO settings ("key", value)
VALUES('DISCARD_RELEASES', NULL);

DELETE FROM settings
WHERE key IN (
    'DISCARD_BETA',
    'DISCARD_DEBUG',
    'DISCARD_DEMO',
    'DISCARD_CASTLEVANIA_ANNIVERSARY_COLLECTION',
    'DISCARD_CLASSIC_MINI',
    'DISCARD_COLLECTION_OF_MANA',
    'DISCARD_GOG',
    'DISCARD_PROGRAM',
    'DISCARD_PROTO',
    'DISCARD_SAMPLE',
    'DISCARD_SEGA_CHANNEL',
    'DISCARD_SNES_MINI',
    'DISCARD_SONIC_CLASSIC_COLLECTION',
    'DISCARD_SWITCH_ONLINE',
    'DISCARD_VIRTUAL_CONSOLE',
    'DISCARD_WII'
);
