INSERT OR REPLACE INTO settings ("key", value)
VALUES ('CHD_CD_HUNK_SIZE', NULL);

INSERT OR REPLACE INTO settings ("key", value)
VALUES ('CHD_CD_COMPRESSION_ALGORITHMS', NULL);

INSERT OR REPLACE INTO settings ("key", value)
VALUES ('CHD_DVD_HUNK_SIZE', NULL);

INSERT OR REPLACE INTO settings ("key", value)
VALUES ('CHD_DVD_COMPRESSION_ALGORITHMS', NULL);
