INSERT OR REPLACE INTO settings ("key", value)
VALUES ('CHD_HD_HUNK_SIZE', NULL);

INSERT OR REPLACE INTO settings ("key", value)
VALUES ('CHD_HD_COMPRESSION_ALGORITHMS', NULL);

INSERT OR REPLACE INTO settings ("key", value)
VALUES ('CHD_LD_HUNK_SIZE', NULL);

INSERT OR REPLACE INTO settings ("key", value)
VALUES ('CHD_LD_COMPRESSION_ALGORITHMS', NULL);
