INSERT OR REPLACE INTO settings ("key", value)
VALUES('SEVENZIP_COMPRESSION_ALGORITHM', 'lzma2');

INSERT OR REPLACE INTO settings ("key", value)
VALUES('ZIP_COMPRESSION_ALGORITHM', 'deflate');

INSERT OR REPLACE INTO settings ("key", value)
VALUES('SEVENZIP_ZSTD_COMPRESSION_LEVEL', '19');

INSERT OR REPLACE INTO settings ("key", value)
VALUES('ZIP_ZSTD_COMPRESSION_LEVEL', '19');
