#!/usr/bin/env python3
"""Generate cross-language crypto/key-derivation test vectors for nsz-rs.

Uses the *actual* nsz Python primitives (nsz.nut.aes128, nsz.nut.Keys) with
synthetic keys so the Rust port can assert byte-identical results. CRC32 source
checks are disabled so we can feed arbitrary synthetic source bytes.

Run from the repo root:  python3 nsz-rs/scripts/gen_vectors.py
Writes: nsz-rs/tests/vectors.json
"""
import sys, os, json
from binascii import hexlify as hx, unhexlify as uhx

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO)

from nsz.nut import aes128
from nsz.nut import Keys

# Disable CRC32 source verification so synthetic sources are accepted.
Keys.crc32_checksum = {}


def h(b):
    return hx(b).decode()


def synth(seed_byte, n=16):
    """Deterministic synthetic 16-byte value."""
    return bytes(((seed_byte * 31 + i * 7 + 3) & 0xFF) for i in range(n))


# ---- synthetic key material -------------------------------------------------
SRC = {
    "aes_kek_generation_source": synth(0x01),
    "aes_key_generation_source": synth(0x02),
    "titlekek_source": synth(0x03),
    "key_area_key_application_source": synth(0x04),
    "key_area_key_ocean_source": synth(0x05),
    "key_area_key_system_source": synth(0x06),
}
MASTER_KEYS = {
    0x00: synth(0x10),
    0x05: synth(0x15),
    0x0A: synth(0x1A),
    0x14: synth(0x24),
}

# Populate the module-global keys dict the way load() would.
Keys.keys = {k: h(v) for k, v in SRC.items()}
for idx, mk in MASTER_KEYS.items():
    Keys.keys["master_key_{0:02x}".format(idx)] = h(mk)


def derive_titlekek(master_key):
    crypto = aes128.AESECB(master_key)
    return crypto.decrypt(SRC["titlekek_source"])


def derive_key_area_key(source, master_key):
    return Keys.generateKek(
        source, master_key,
        SRC["aes_kek_generation_source"], SRC["aes_key_generation_source"],
    )


def unwrap_titlekey(wrapped, key_generation):
    return Keys.unwrapAesWrappedTitlekey(wrapped, key_generation)


# ---- build vectors --------------------------------------------------------
vectors = {
    "_comment": "Generated by nsz-rs/scripts/gen_vectors.py from the Python nsz lib. Do not edit by hand.",
    "sources": {k: h(v) for k, v in SRC.items()},
    "master_keys": {format(i, "02x"): h(mk) for i, mk in MASTER_KEYS.items()},
    "titlekeks": {},
    "key_area_keys": {},
    "unwrap_titlekey": [],
    "ctr": [],
    "xtsn": [],
    "mul_alpha_le": [],
}

for idx, mk in MASTER_KEYS.items():
    key = format(idx, "02x")
    vectors["titlekeks"][key] = h(derive_titlekek(mk))
    vectors["key_area_keys"][key] = {
        "application": h(derive_key_area_key(SRC["key_area_key_application_source"], mk)),
        "ocean": h(derive_key_area_key(SRC["key_area_key_ocean_source"], mk)),
        "system": h(derive_key_area_key(SRC["key_area_key_system_source"], mk)),
    }
    # unwrap: wrap a synthetic titlekey with the application-derived kek, then unwrap.
    kek = derive_key_area_key(SRC["key_area_key_application_source"], mk)
    fake_titlekey = synth(0x40 + idx)
    wrapped = aes128.AESECB(kek).encrypt(fake_titlekey)
    unwrapped = unwrap_titlekey(wrapped, idx)
    assert unwrapped == fake_titlekey, "unwrap roundtrip failed in generator"
    vectors["unwrap_titlekey"].append({
        "key_generation": idx,
        "wrapped": h(wrapped),
        "expected": h(unwrapped),
    })

# CTR vectors: exercise block-aligned and unaligned offsets.
ctr_key = synth(0x71)
ctr_nonce = synth(0x72) + b"\x00" * 0  # 16 bytes; only first 8 used as prefix
for off in (0, 1, 15, 16, 17, 0x1000, 0x10001, 0x100000, 0x10000F):
    data = bytes((i * 13 + 5) & 0xFF for i in range(64))
    c = aes128.AESCTR(ctr_key, ctr_nonce, offset=off)
    ct = c.encrypt(data)
    vectors["ctr"].append({
        "key": h(ctr_key),
        "nonce": h(ctr_nonce),
        "offset": off,
        "plaintext": h(data),
        "ciphertext": h(ct),
    })

# XTSN vectors: Nintendo sector tweak, sector_size 0x200.
xts_k1 = synth(0x81)
xts_k2 = synth(0x82)
for sector in (0, 1, 2, 0xFF, 0x100):
    data = bytes((i * 17 + 11) & 0xFF for i in range(0x200))
    x = aes128.AESXTSN((xts_k1, xts_k2), sector_size=0x200, sector=sector)
    ct = x.encrypt(data)
    vectors["xtsn"].append({
        "key1": h(xts_k1),
        "key2": h(xts_k2),
        "sector_size": 0x200,
        "sector": sector,
        "plaintext": h(data),
        "ciphertext": h(ct),
    })

# mul_alpha_le direct vectors (the GF(2^128) LE-alpha tweak step).
for i in range(6):
    t = bytes((i * 29 + 200) & 0xFF for _ in range(16))
    # force a high-bit-set case on the last vector to exercise the reduction
    if i == 5:
        t = b"\x00" * 15 + b"\x80"
    vectors["mul_alpha_le"].append({
        "input": h(t),
        "output": h(aes128._mul_alpha_le(t)),
    })

out = os.path.join(REPO, "nsz-rs", "tests", "vectors.json")
with open(out, "w") as f:
    json.dump(vectors, f, indent=2)

# Also emit a self-contained Rust module so the integration test needs no JSON dep.
def rs_strs(items):
    return ",\n    ".join(items)

lines = []
lines.append("// @generated by nsz-rs/scripts/gen_vectors.py — DO NOT EDIT BY HAND")
lines.append("// Cross-language crypto/key-derivation vectors from the Python nsz lib.")
lines.append("#![allow(dead_code)]")
lines.append("")
lines.append("pub const SOURCES: [(&str, &str); {}] = [".format(len(vectors["sources"])))
lines.append("    " + rs_strs('("{0}", "{1}")'.format(k, v) for k, v in vectors["sources"].items()))
lines.append("];")
lines.append("")
lines.append("pub const MASTER_KEYS: [(&str, &str); {}] = [".format(len(vectors["master_keys"])))
lines.append("    " + rs_strs('("{0}", "{1}")'.format(k, v) for k, v in vectors["master_keys"].items()))
lines.append("];")
lines.append("")
lines.append("pub const TITLEKEKS: [(&str, &str); {}] = [".format(len(vectors["titlekeks"])))
lines.append("    " + rs_strs('("{0}", "{1}")'.format(k, v) for k, v in vectors["titlekeks"].items()))
lines.append("];")
lines.append("")
lines.append("pub const KEY_AREA_KEYS: [(&str, (&str, &str, &str)); {}] = [".format(len(vectors["key_area_keys"])))
lines.append("    " + rs_strs('("{0}", ("{1}", "{2}", "{3}"))'.format(k, v["application"], v["ocean"], v["system"]) for k, v in vectors["key_area_keys"].items()))
lines.append("];")
lines.append("")
lines.append("pub const UNWRAP_TITLEKEY: [(&str, &str, &str); {}] = [".format(len(vectors["unwrap_titlekey"])))
lines.append("    " + rs_strs('("{0:x}", "{1}", "{2}")'.format(u["key_generation"], u["wrapped"], u["expected"]) for u in vectors["unwrap_titlekey"]))
lines.append("];")
lines.append("")
lines.append("pub const CTR: [(&str, &str, u64, &str, &str); {}] = [".format(len(vectors["ctr"])))
lines.append("    " + rs_strs('("{0}", "{1}", {2}, "{3}", "{4}")'.format(c["key"], c["nonce"], c["offset"], c["plaintext"], c["ciphertext"]) for c in vectors["ctr"]))
lines.append("];")
lines.append("")
lines.append("pub const XTSN: [(&str, &str, u64, &str, &str); {}] = [".format(len(vectors["xtsn"])))
lines.append("    " + rs_strs('("{0}", "{1}", {2}, "{3}", "{4}")'.format(x["key1"], x["key2"], x["sector"], x["plaintext"], x["ciphertext"]) for x in vectors["xtsn"]))
lines.append("];")
lines.append("")
lines.append("pub const MUL_ALPHA_LE: [(&str, &str); {}] = [".format(len(vectors["mul_alpha_le"])))
lines.append("    " + rs_strs('("{0}", "{1}")'.format(m["input"], m["output"]) for m in vectors["mul_alpha_le"]))
lines.append("];")
lines.append("")

rs_out = os.path.join(REPO, "nsz-rs", "tests", "vectors_gen.rs")
with open(rs_out, "w") as f:
    f.write("\n".join(lines))
print("wrote", out)
print("wrote", rs_out)
print("titlekek[00] =", vectors["titlekeks"]["00"])
print("key_area[05].application =", vectors["key_area_keys"]["05"]["application"])
print("ctr[0] ct[:32] =", vectors["ctr"][0]["ciphertext"][:32])
print("xtsn[0] ct[:32] =", vectors["xtsn"][0]["ciphertext"][:32])
