//! M1 cross-language acceptance gate: the Rust crypto + key derivation must match
//! the Python `nsz` implementation byte-for-byte on synthetic keys.
//!
//! Vectors are generated by `nsz-rs/scripts/gen_vectors.py` into `vectors_gen.rs`.

#[path = "vectors_gen.rs"]
mod v;

use nsz_rs::crypto::{ctr, xtsn};
use nsz_rs::keys::{KeyArea, Keys};

fn hx(s: &str) -> Vec<u8> {
    hex::decode(s).unwrap()
}

fn key16(s: &str) -> [u8; 16] {
    let v = hx(s);
    let mut a = [0u8; 16];
    a.copy_from_slice(&v);
    a
}

fn build_keys() -> Keys {
    let mut text = String::new();
    for (k, val) in v::SOURCES {
        text.push_str(&format!("{k} = {val}\n"));
    }
    for (rev, val) in v::MASTER_KEYS {
        text.push_str(&format!("master_key_{rev} = {val}\n"));
    }
    // Synthetic keys: skip CRC32 source verification.
    Keys::from_str(&text, false).expect("keys parse")
}

#[test]
fn titlekek_derivation_matches_python() {
    let keys = build_keys();
    for (rev, expected) in v::TITLEKEKS {
        let r = usize::from_str_radix(rev, 16).unwrap();
        let got = keys.title_kek(r).unwrap();
        assert_eq!(hex::encode(got), *expected, "titlekek[{rev}]");
    }
}

#[test]
fn key_area_key_derivation_matches_python() {
    let keys = build_keys();
    for (rev, (app, ocean, sys)) in v::KEY_AREA_KEYS {
        let r = usize::from_str_radix(rev, 16).unwrap();
        assert_eq!(
            hex::encode(keys.key_area_key(r, KeyArea::Application).unwrap()),
            *app,
            "kaa[{rev}]"
        );
        assert_eq!(
            hex::encode(keys.key_area_key(r, KeyArea::Ocean).unwrap()),
            *ocean,
            "kao[{rev}]"
        );
        assert_eq!(
            hex::encode(keys.key_area_key(r, KeyArea::System).unwrap()),
            *sys,
            "kas[{rev}]"
        );
    }
}

#[test]
fn unwrap_titlekey_matches_python() {
    let keys = build_keys();
    for (gen, wrapped, expected) in v::UNWRAP_TITLEKEY {
        let g = usize::from_str_radix(gen, 16).unwrap();
        let w = key16(wrapped);
        let got = keys.unwrap_title_key(&w, g).unwrap();
        assert_eq!(hex::encode(got), *expected, "unwrap gen {gen}");
    }
}

#[test]
fn seekable_ctr_matches_python() {
    for (key, nonce, offset, pt, ct) in v::CTR {
        let k = key16(key);
        let n = key16(nonce);
        let mut buf = hx(pt);
        ctr::keystream_xor(&k, &n, offset, &mut buf);
        assert_eq!(hex::encode(&buf), *ct, "ctr offset {offset}");
        // CTR is symmetric: decrypting the ciphertext returns the plaintext.
        let mut back = hx(ct);
        ctr::keystream_xor(&k, &n, offset, &mut back);
        assert_eq!(hex::encode(&back), *pt, "ctr roundtrip offset {offset}");
    }
}

#[test]
fn xtsn_matches_python() {
    for (k1, k2, sector, pt, ct) in v::XTSN {
        let key1 = key16(k1);
        let key2 = key16(k2);
        let mut buf = hx(pt);
        xtsn::crypt(&key1, &key2, 0x200, sector, &mut buf, false);
        assert_eq!(hex::encode(&buf), *ct, "xtsn encrypt sector {sector}");
        // decrypt returns plaintext
        let mut back = hx(ct);
        xtsn::crypt(&key1, &key2, 0x200, sector, &mut back, true);
        assert_eq!(hex::encode(&back), *pt, "xtsn decrypt sector {sector}");
    }
}

#[test]
fn mul_alpha_le_matches_python() {
    for (input, output) in v::MUL_ALPHA_LE {
        let t = key16(input);
        let got = xtsn::mul_alpha_le(t);
        assert_eq!(hex::encode(got), *output, "mul_alpha_le {input}");
    }
}
